[package]
name = "hypersync-solana-schema"
version = "0.0.3"
edition = "2021"
rust-version = "1.75"
description = "Arrow schemas for Solana HyperSync tables"
license = "MPL-2.0"
repository = "https://github.com/enviodev/hypersync-client-solana"
homepage = "https://github.com/enviodev/hypersync-client-solana"
readme = "../README.md"
keywords = ["solana", "hypersync", "envio", "arrow"]
categories = ["api-bindings", "data-structures"]

[dependencies]
arrow = "57"
