/* auto-generated by NAPI-RS */
/* eslint-disable */

/** One decoded row: column name (`snake_case`) to value. */
export type RowObject = Record<string, unknown>

/* --- generated below --- *//** Solana HyperSync client. */
export declare class SolanaClient {
  /** Create a new client with the given config. */
  constructor(cfg: ClientConfig)
  /**
   * Create a new client with the given config and a custom user agent.
   *
   * Mirrors the EVM HyperSync client's `newWithAgent`.
   */
  static newWithAgent(cfg: ClientConfig, userAgent: string): SolanaClient
  /** Get the current chain height (latest slot). */
  getHeight(): Promise<number>
  /**
   * Run a single query and return the decoded response.
   *
   * The server may return fewer slots than the range you requested;
   * inspect `response.nextSlot` to know where to continue from.
   *
   * Named to match the EVM HyperSync client's `get`, so `get` and
   * `getWithRateLimit` read as the pair they are.
   */
  get(query: SolanaQuery): Promise<QueryResponse>
  /**
   * Run a single query and return the decoded response along with rate
   * limit information from the server.
   *
   * Retry and back-off behaviour is identical to `get`: a 429 is slept out
   * against `x-ratelimit-reset` and retried. Named and shaped to match the
   * EVM client's `getWithRateLimit`.
   */
  getWithRateLimit(query: SolanaQuery): Promise<QueryResponseWithRateLimit>
  /**
   * Get the most recently observed rate limit information.
   * Returns null if no query response has included rate limit headers yet.
   */
  rateLimitInfo(): RateLimitInfo | null
  /**
   * Wait until the current rate limit window resets.
   * Returns immediately if no rate limit info has been observed or quota remains.
   */
  waitForRateLimit(): Promise<void>
}

/**
 * Filter for selecting rows of the merged `account_activity` table. All
 * non-empty fields are AND-ed. Because the table carries the native SOL and
 * SPL token sides on one row, one selection expresses what previously needed
 * a native-balance selection and a token-balance selection together.
 */
export interface AccountActivitySelection {
  /**
   * Restrict to rows carrying a given side of the merge: "native",
   * "token", or both. A row carrying both sides matches either value, so
   * `["native"]` is the row set the removed `balances` table held.
   */
  kind?: Array<string>
  account?: Array<string>
  transactionId?: Array<string>
  mint?: Array<string>
  /**
   * Matches either the pre or the post owner (the stored column is split
   * so an in-transaction owner change stays visible).
   */
  owner?: Array<string>
  programId?: Array<string>
  /**
   * Position flags. A row whose flag is null (the source could not derive
   * it) matches neither true nor false.
   */
  isSigner?: boolean
  isWritable?: boolean
  isFeePayer?: boolean
  fromLookupTable?: boolean
}

/** Configuration for the Solana HyperSync client. */
export interface ClientConfig {
  /** Base URL of the HyperSync server (e.g. "https://solana.hypersync.xyz"). */
  url: string
  /** API token for authenticated requests. Sent as a bearer token. */
  apiToken?: string
  /** Milliseconds to wait for a response before timing out. Default: 30000. */
  httpReqTimeoutMillis?: number
  /** Maximum number of retries per request. Default: 12. */
  maxNumRetries?: number
  /** Initial backoff before the first retry, in milliseconds. Default: 500. */
  retryBaseMs?: number
  /** Maximum backoff between retries, in milliseconds. Default: 5000. */
  retryCeilingMs?: number
  /**
   * Whether to proactively sleep when the rate limit is exhausted instead
   * of sending requests that will be rejected with 429. Default: true.
   */
  proactiveRateLimitSleep?: boolean
}

/**
 * Per-table field selection. Each list is a set of column names in `snake_case`.
 * An empty (or missing) list means "return all columns for that table".
 */
export interface FieldSelection {
  block?: Array<string>
  transaction?: Array<string>
  instructionCall?: Array<string>
  /**
   * @deprecated renamed to `instructionCall`; still honored when
   * `instructionCall` is absent.
   */
  instruction?: Array<string>
  log?: Array<string>
  accountActivity?: Array<string>
  reward?: Array<string>
}

/** Filter for selecting instruction calls. All non-empty fields are AND-ed. */
export interface InstructionSelection {
  executingAccount?: Array<string>
  /**
   * @deprecated renamed to `executingAccount`; still honored when
   * `executingAccount` is absent.
   */
  programId?: Array<string>
  d1?: Array<string>
  d2?: Array<string>
  d4?: Array<string>
  d8?: Array<string>
  a0?: Array<string>
  a1?: Array<string>
  a2?: Array<string>
  a3?: Array<string>
  a4?: Array<string>
  a5?: Array<string>
  a6?: Array<string>
  a7?: Array<string>
  a8?: Array<string>
  a9?: Array<string>
  /** None: match both outer and inner. true: inner only. false: outer only. */
  isInner?: boolean
  /**
   * Success of the PARENT transaction. None: match instructions of both
   * successful and failed transactions. true: successful only. false:
   * failed only. NOTE: servers running the failed-transaction trim store
   * no instruction rows for failed transactions, so `false` matches
   * nothing there; query failed transactions via the transactions table's
   * `success` filter instead.
   */
  txSuccess?: boolean
  /**
   * @deprecated renamed to `txSuccess`; still honored when `txSuccess` is
   * absent.
   */
  isCommitted?: boolean
}

/** Filter for selecting logs. All non-empty fields are AND-ed. */
export interface LogSelection {
  programId?: Array<string>
  /**
   * Log kinds to match: invoke/success/failed/consumed/log/data/other.
   * SQD-ingested and default RPC-ingested ranges only carry
   * log/data/other rows.
   */
  kind?: Array<string>
}

/** Response from a Solana HyperSync query. */
export interface QueryResponse {
  /** Next slot to query from (for pagination). */
  nextSlot: number
  /** Number of bytes in the raw server response (useful for tuning). */
  responseBytes: number
  /**
   * Reorg guard describing the server's in-memory head window, when the
   * server has one to report.
   */
  rollbackGuard?: RollbackGuard
  /**
   * Per-table row arrays. Keys are table names: `blocks`, `transactions`,
   * `instruction_calls`, `logs`, `account_activity`, `rewards`.
   */
  tables: Record<string, Array<RowObject>>
}

/**
 * Response from `getWithRateLimit`. Shape mirrors the EVM client's
 * `QueryResponseWithRateLimit`.
 */
export interface QueryResponseWithRateLimit {
  /** The decoded query response. */
  response: QueryResponse
  /** Rate limit information from response headers. */
  rateLimit: RateLimitInfo
}

/**
 * Rate limit information from response headers. Shape mirrors the EVM
 * client's RateLimitInfo.
 */
export interface RateLimitInfo {
  /** Total request quota for the current window (`x-ratelimit-limit`). */
  limit?: number
  /**
   * Remaining budget in the current window (`x-ratelimit-remaining`).
   * Budget units, not request count: divide by `cost` for requests left.
   */
  remaining?: number
  /** Seconds until the window resets (`x-ratelimit-reset`). */
  resetSecs?: number
  /** Budget consumed per request (`x-ratelimit-cost`). */
  cost?: number
}

/**
 * Reorg guard attached to query responses: the server's in-memory head
 * window (its last block, plus the first slot of the window and that slot's
 * parent hash), so a consumer can detect a fork and unwind before committing.
 * Shape mirrors the EVM client's rollbackGuard with Solana naming.
 */
export interface RollbackGuard {
  /** The last slot in the server's in-memory window. */
  slotNumber: number
  /** Timestamp of the last block. */
  timestamp: number
  /** Blockhash of the last block (base58). */
  blockhash: string
  /** The first slot in the server's in-memory window. */
  firstSlotNumber: number
  /** Previous blockhash of the first block in the window (base58). */
  firstPreviousBlockhash: string
}

/**
 * Top-level Solana HyperSync query. Returns block bundles matching the
 * given filters within `[from_slot, to_slot)`.
 */
export interface SolanaQuery {
  /** Inclusive start slot. */
  fromSlot: number
  /** Exclusive end slot. If omitted, queries run to the current height. */
  toSlot?: number
  instructionCalls?: Array<InstructionSelection>
  /**
   * @deprecated renamed to `instructionCalls`; still honored when
   * `instructionCalls` is absent.
   */
  instructions?: Array<InstructionSelection>
  transactions?: Array<TransactionSelection>
  logs?: Array<LogSelection>
  accountActivity?: Array<AccountActivitySelection>
  /**
   * @deprecated the server removed this flag; setting it to true is an
   * error. Use `accountActivity: [{}]` to request every account activity
   * row in range.
   */
  includeAccountActivity?: boolean
  includeAllBlocks?: boolean
  /** Per-table field selection (which columns to return). */
  fieldSelection?: FieldSelection
  maxNumBlocks?: number
  maxNumTransactions?: number
  maxNumInstructions?: number
  maxNumLogs?: number
  maxNumAccountActivity?: number
}

/** Filter for selecting transactions. All non-empty fields are AND-ed. */
export interface TransactionSelection {
  feePayer?: Array<string>
  /** Base58 `signatures[0]`, the canonical Solana transaction signature. */
  transactionId?: Array<string>
  /** Position of the transaction within its block. */
  transactionIndex?: Array<number>
  success?: boolean
}
