/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Solana HyperSync client. */
export declare class SolanaClient {
  /** Create a new client with the given config. */
  constructor(cfg: ClientConfig)
  /**
   * Create a new client with the given config and a custom user agent.
   *
   * Mirrors the EVM and Fuel HyperSync clients' `createWithAgent`.
   */
  static createWithAgent(cfg: ClientConfig, userAgent: string): SolanaClient
  /** Get the current chain height (latest slot). */
  getHeight(): Promise<number>
  /**
   * Run a single query and return the decoded response.
   *
   * The server may return fewer slots than the range you requested;
   * inspect `response.nextSlot` to know where to continue from.
   */
  query(query: SolanaQuery): Promise<QueryResponse>
}

/**
 * Filter for selecting rows of the merged `account_activity` table. All
 * non-empty fields are AND-ed. Because the table carries the native SOL and
 * SPL token sides on one row, one selection expresses what previously needed
 * a native-balance selection and a token-balance selection together.
 */
export interface AccountActivitySelection {
  account?: Array<string>
  mint?: Array<string>
  owner?: Array<string>
  programId?: Array<string>
}


/** Configuration for the Solana HyperSync client. */
export interface ClientConfig {
  /** Base URL of the HyperSync server (e.g. "https://solana.hypersync.xyz"). */
  url: string
  /** Bearer token for authenticated requests. */
  bearerToken?: string
  /** Milliseconds to wait for a response before timing out. Default: 30000. */
  httpReqTimeoutMillis?: number
  /** Maximum number of retries per request. Default: 12. */
  maxNumRetries?: number
  /** Initial backoff before the first retry, in milliseconds. Default: 500. */
  retryBaseMs?: number
  /** Maximum backoff between retries, in milliseconds. Default: 5000. */
  retryCeilingMs?: number
}

/**
 * Per-table field selection. Each list is a set of column names in `snake_case`.
 * An empty (or missing) list means "return all columns for that table".
 */
export interface FieldSelection {
  block?: Array<string>
  transaction?: Array<string>
  instructionCall?: Array<string>
  /**
   * @deprecated renamed to `instructionCall`; still honored when
   * `instructionCall` is absent.
   */
  instruction?: Array<string>
  log?: Array<string>
  accountActivity?: Array<string>
  reward?: Array<string>
}

/** Filter for selecting instructions. All non-empty fields are AND-ed. */
export interface InstructionSelection {
  executingAccount?: Array<string>
  /**
   * @deprecated renamed to `executingAccount`; still honored when
   * `executingAccount` is absent.
   */
  programId?: Array<string>
  d1?: Array<string>
  d2?: Array<string>
  d4?: Array<string>
  d8?: Array<string>
  a0?: Array<string>
  a1?: Array<string>
  a2?: Array<string>
  a3?: Array<string>
  a4?: Array<string>
  a5?: Array<string>
  a6?: Array<string>
  a7?: Array<string>
  a8?: Array<string>
  a9?: Array<string>
  /** None: match both outer and inner. true: inner only. false: outer only. */
  isInner?: boolean
  /**
   * Commit status of the parent transaction. None: match both committed and
   * failed. true: successful transactions only. false: failed only.
   */
  isCommitted?: boolean
}

/** Filter for selecting logs. All non-empty fields are AND-ed. */
export interface LogSelection {
  programId?: Array<string>
  kind?: Array<string>
}

/** Response from a Solana HyperSync query. */
export interface QueryResponse {
  /** Next slot to query from (for pagination). */
  nextSlot: number
  /** Number of bytes in the raw server response (useful for tuning). */
  responseBytes: number
  /**
   * Per-table row arrays. Keys are table names: `blocks`, `transactions`,
   * `instructions`, `logs`, `balances`, `token_balances`, `rewards`.
   */
  tables: Record<string, Array<RowObject>>
}

/**
 * Top-level Solana HyperSync query. Returns block bundles matching the
 * given filters within `[from_slot, to_slot)`.
 */
export interface SolanaQuery {
  /** Inclusive start slot. */
  fromSlot: number
  /** Exclusive end slot. If omitted, queries run to the current height. */
  toSlot?: number
  instructionCalls?: Array<InstructionSelection>
  /**
   * @deprecated renamed to `instructionCalls`; still honored when
   * `instructionCalls` is absent.
   */
  instructions?: Array<InstructionSelection>
  transactions?: Array<TransactionSelection>
  logs?: Array<LogSelection>
  accountActivity?: Array<AccountActivitySelection>
  includeAllBlocks?: boolean
  /**
   * Return merged account activity for the matched result set without
   * requiring `include_all_blocks`.
   */
  includeAccountActivity?: boolean
  /** Per-table field selection (which columns to return). */
  fieldSelection?: FieldSelection
  maxNumBlocks?: number
  maxNumTransactions?: number
  maxNumInstructions?: number
  maxNumLogs?: number
  maxNumAccountActivity?: number
}

/** Filter for selecting transactions. All non-empty fields are AND-ed. */
export interface TransactionSelection {
  feePayer?: Array<string>
  /** Base58 `signatures[0]`, the canonical Solana transaction signature. */
  transactionId?: Array<string>
  /** Position of the transaction within its block. */
  transactionIndex?: Array<number>
  success?: boolean
}
