/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Solana HyperSync client. */
export declare class SolanaClient {
  /** Create a new client with the given config. */
  constructor(cfg: ClientConfig)
  /**
   * Create a new client with the given config and a custom user agent.
   *
   * Mirrors the EVM and Fuel HyperSync clients' `createWithAgent`.
   */
  static createWithAgent(cfg: ClientConfig, userAgent: string): SolanaClient
  /** Get the current chain height (latest slot). */
  getHeight(): Promise<number>
  /**
   * Run a single query and return the decoded response.
   *
   * The server may return fewer slots than the range you requested;
   * inspect `response.nextSlot` to know where to continue from.
   */
  query(query: SolanaQuery): Promise<QueryResponse>
}

/** Configuration for the Solana HyperSync client. */
export interface ClientConfig {
  /** Base URL of the HyperSync server (e.g. "https://solana.hypersync.xyz"). */
  url: string
  /** Bearer token for authenticated requests. */
  bearerToken?: string
  /** Milliseconds to wait for a response before timing out. Default: 30000. */
  httpReqTimeoutMillis?: number
  /** Maximum number of retries per request. Default: 12. */
  maxNumRetries?: number
  /** Initial backoff before the first retry, in milliseconds. Default: 500. */
  retryBaseMs?: number
  /** Maximum backoff between retries, in milliseconds. Default: 5000. */
  retryCeilingMs?: number
}

/**
 * Per-table field selection. Each list is a set of column names in `snake_case`.
 * An empty (or missing) list means "return all columns for that table".
 */
export interface FieldSelection {
  block?: Array<string>
  transaction?: Array<string>
  instruction?: Array<string>
  log?: Array<string>
  balance?: Array<string>
  tokenBalance?: Array<string>
  reward?: Array<string>
}

/** Filter for selecting instructions. All non-empty fields are AND-ed. */
export interface InstructionSelection {
  programId?: Array<string>
  d1?: Array<string>
  d2?: Array<string>
  d4?: Array<string>
  d8?: Array<string>
  a0?: Array<string>
  a1?: Array<string>
  a2?: Array<string>
  a3?: Array<string>
  a4?: Array<string>
  a5?: Array<string>
  a6?: Array<string>
  a7?: Array<string>
  a8?: Array<string>
  a9?: Array<string>
  /** None: match both outer and inner. true: inner only. false: outer only. */
  isInner?: boolean
}

/** Filter for selecting logs. All non-empty fields are AND-ed. */
export interface LogSelection {
  programId?: Array<string>
  kind?: Array<string>
}

/** Response from a Solana HyperSync query. */
export interface QueryResponse {
  /** Next slot to query from (for pagination). */
  nextSlot: number
  /** Number of bytes in the raw server response (useful for tuning). */
  responseBytes: number
  /**
   * Per-table row arrays. Keys are table names: `blocks`, `transactions`,
   * `instructions`, `logs`, `balances`, `token_balances`, `rewards`.
   */
  tables: Record<string, Array<RowObject>>
}

/**
 * Top-level Solana HyperSync query. Returns block bundles matching the
 * given filters within `[from_slot, to_slot)`.
 */
export interface SolanaQuery {
  /** Inclusive start slot. */
  fromSlot: number
  /** Exclusive end slot. If omitted, queries run to the current height. */
  toSlot?: number
  instructions?: Array<InstructionSelection>
  transactions?: Array<TransactionSelection>
  logs?: Array<LogSelection>
  includeAllBlocks?: boolean
  /** Per-table field selection (which columns to return). */
  fieldSelection?: FieldSelection
  maxNumBlocks?: number
  maxNumTransactions?: number
  maxNumInstructions?: number
  maxNumLogs?: number
}

/** Filter for selecting transactions. All non-empty fields are AND-ed. */
export interface TransactionSelection {
  feePayer?: Array<string>
  success?: boolean
}
